exclude: "^.*\\.dat$"
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-json
    -   id: check-toml
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black

-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    -   id: isort

-   repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.4.0
    hooks:
    -   id: editorconfig-checker

-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        entry: pflake8
        additional_dependencies:
        -   flake8-bandit==3.0.0
        -   flake8-bugbear==22.6.22
        -   flake8-builtins==1.5.3
        -   flake8-comprehensions==3.10.0
        -   flake8-docstrings==1.6.0
        -   flake8-pytest-style==1.6.0
        -   pep8-naming==0.13.0
        -   pyproject-flake8==0.0.1a4

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
    -   id: mypy
        args: []
        additional_dependencies:
        -   pytest-mock==3.8.1
        -   pytest==7.1.2
        -   tomlkit==0.11.0
        -   types-PyYAML==6.0.9
        -   types-requests==2.28.0

-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
    -   id: shellcheck
        args: [-x]

-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
    -   id: gitlint
